# Generated by Django 5.0.1 on 2024-02-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
    ]
