# Generated by Django 5.0.1 on 2024-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('free', 'Free'), ('busy', 'Busy'), ('reserved', 'Reserved')], default='free', max_length=8),
        ),
    ]
